### ISSUE TITLE
Demo page

### ISSUE THREAD

**Issue by mohdhazwan** [tomgrek/masonic#1]
Any plan to create a demo page soon?

**Comment by tomgrek** [comment]
Sure, give me 24 hours and I'll put a page up.

**Comment by tomgrek** [comment]
Thanks for closing. Demo is at [tomgrek.com/masonicdemo](http://www.tomgrek.com/masonicdemo/)

**Comment by mohdhazwan** [comment]
Oh great! One more, I think you missed the meta viewport. It displays desktop view on real devices
Thanks
